name: conv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - pip:
      - requests>=2.28,<3
      - ngff-zarr==0.46.0
      - zarrista==0.1.0
      - zarr>=3,<4
      - bia-ro-crate-validator
